spring.application.name=reservation-backend

# URL de la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/g1-reservation
# Usuario de la base de datos
spring.datasource.username=postgres
# Contraseña de la base de datos
spring.datasource.password=Palomino13

# Actualice las tablas en la base de datos
spring.jpa.hibernate.ddl-auto=update

# Muestre las consultas SQL en la consola
spring.jpa.show-sql=true
# Formatee las consultas SQL
spring.jpa.properties.hibernate.format_sql=true

server.port=8082

# Evita error de permisos en Windows al persistir sesiones en TEMP
server.servlet.session.persistent=false
